<a href="https://colab.research.google.com/github/kaurarshmeet/pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [2]:
!nvidia-smi

Thu Jun  5 18:19:41 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.6.0+cu124


## Different kinds of tensors:
*   Scalar = one number
*   Tensor = a tupule

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim # 0 dimensions for a scalar.

0

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim # 1 dimensions for a vector.

1

In [9]:
vector.shape # 2 by 1 => 2 elements in the vector.

torch.Size([2])

In [10]:
# matrix - a group of vectors.
MATRIX = torch.tensor(
    [[7,8],
    [9,10]]
)
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim # 2

2

In [12]:
MATRIX.shape # 2 by 2

torch.Size([2, 2])

In [13]:
# Tensor - a group of matrices
TENSOR = torch.tensor(
    [[
        [[1,2,3],
       [3,6,9]],

        [[1,3,4],
         [1,3,4]]

        ],

        [
           [[1,3,2],
            [1,5,8]],

           [[1,2,3],
            [4,5,6]]
        ]
     ]
)

TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9]],

         [[1, 3, 4],
          [1, 3, 4]]],


        [[[1, 3, 2],
          [1, 5, 8]],

         [[1, 2, 3],
          [4, 5, 6]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape # 2 sets of 2 (2 x 3 matrices).

torch.Size([2, 2, 2, 3])

## Random Tensors

* Many neural networks start with tensors full of random numbers, then update those to better understand data.

In [16]:
# by default, they will be float data type.
random_tensor = torch.rand(2, 3, 4) # 2 (3 x 4 matrices) filled with random numbers.
random_tensor

tensor([[[0.7965, 0.5749, 0.9597, 0.4857],
         [0.7046, 0.0229, 0.6129, 0.9999],
         [0.6780, 0.7045, 0.4562, 0.2179]],

        [[0.1999, 0.1037, 0.5628, 0.7060],
         [0.2499, 0.3388, 0.0426, 0.7213],
         [0.1400, 0.2021, 0.9174, 0.1004]]])

In [17]:
zeros = torch.zeros(size=(2,3,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
# multiplying two tensors
random_tensor * zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
random_tensor.dtype

torch.float32

## Creating a Range of Tensors

In [20]:
# creating a tensor from the range.
# arange(start, stop, step)
# [start, start + step...stop) not end-inclusive.
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
skipping = torch.arange(0,10,2)
skipping

tensor([0, 2, 4, 6, 8])

In [22]:
# Create a copy tensor (in terms of shape)

# creates a tensor with the same shape.
ten_zeros = torch.zeros_like(input=skipping)
ten_zeros

ten_ones = torch.ones_like(input = skipping)
ten_ones

tensor([1, 1, 1, 1, 1])

## Tensor Datatypes

Big issues in PyTorch / deep learning
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on right device.

In [23]:
float_32_tensor = torch.rand(2,3)
float_32_tensor.dtype # by default, float 32.

torch.float32

In [24]:
# tensor fields - don't always have to specify these.
fields = torch.tensor([1,3,3],
                      dtype=None, # still creates float 32 by default.
                                  # may want to demote to torch.half to run faster
                                  # upgrade to torch.double for more precision.
                      device = None, # what device is the tensor on
                      requires_grad = False) # whether or not to track gradients with tensor operations

In [25]:
float_16_tensor = fields.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
fields * float_16_tensor # everything gets depreciated to float16
# sometimes it works
# sometimes it dont work

tensor([1., 9., 9.], dtype=torch.float16)

## Tensor Attributes

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
# still works!
float_16_tensor * int_32_tensor

tensor([ 3., 18., 27.], dtype=torch.float16)

Important information from tensors:
- just use the instance variables
`tensor.dtype`,   `tensor.shape`,   `tensor.device`

In [29]:
# getting information from tensors

some_tensor = torch.rand(3,4)
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

## Manipulating Tensors / Tensor Operations

Tensor Operations:
- addition, subtraction, multiplication element wise, division
- matrix multiplication

In [30]:
# addition
tensor = torch.tensor([1,2,3])
tensor + 10 # adds 10 to each element.

tensor([11, 12, 13])

In [31]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [32]:
# subtraction
tensor - 10

tensor([-9, -8, -7])

In [33]:
# pytorch inbuilt functions
# generally, just use the operators.
torch.mul(tensor, 10) # multiplication

tensor([10, 20, 30])

In [34]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two conditions

- (anything1, n) @ (n, anything2) is good.
- resulting shape will be (anything1, anything2)

In [35]:
 print(tensor)
 tensor * tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [36]:
# even though tensor is (1, 2, 3), when you square it
# it'll assume (1 2 3) horizontal and (1) vertical
                                     #(2)
                                     #(3)
torch.matmul(tensor, tensor) # clearer

tensor(14)

In [37]:
# mm won't work here because it's not flipping horizontal and vertical here
# torch.mm(tensor,tensor)

# this will work because dimensions are explicitly correct.
torch.mm(torch.rand(3,2), torch.rand(2,4))

tensor([[0.5689, 0.7163, 0.7262, 0.5058],
        [0.4958, 0.6901, 0.5342, 0.4427],
        [0.3004, 0.3233, 0.4659, 0.2655]])

In [38]:
tensor @ tensor # same thing

tensor(14)

In [39]:
# multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

tensor(14)

In [40]:
tensor[i] # each tensor element is a scalar, tensor data type though.

tensor(3)

In [41]:
# implementing the matrix multiplication
A = torch.tensor([[1,2],
                  [3,4],
                  [5,6]]) # 3 x 2
B = torch.tensor([[7,8],
                  [9,10],
                  [11,12]]) # 3 x 2
# fixing shape issues => take the transpose
B.T # columns become rows, 2 x 3

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [42]:
B.T @ A # 2 x 2

tensor([[ 89, 116],
        [ 98, 128]])

## Min, Max, etc.

In [43]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
torch.min(x), x.min() # same thing.

(tensor(0), tensor(0))

In [45]:
# same thing for max

In [46]:
# torch.mean function requires tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) # need to convert to float for the mean.

tensor(45.)

In [47]:
# finding position in tensor which has the minimum value
x.argmin() # tensor(0) means index 0

tensor(0)

In [48]:
x.argmax(), x[9] # index 9

(tensor(9), tensor(90))

# Reshaping, Viewing, Stacking

* Reshaping - reshaping input tensors to another shape.
* View - shares memory with original tensor.
* Stacking - combine multiple tensors on top of each other
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions swapped in a certain way.

In [49]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
# Reshaping - reshape dimensions, must be compatible with original size.
# may or may not share memory with original tensor.
# x_reshape = x.reshape(1,7) # invalid bc we have more than 7 elements.
x_reshape = x.reshape(9,1) # we have 9 elements so fine.
x_reshape
x_reshape = x.reshape(3,3) # we have 9 elements, also fine
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [51]:
# View - very similar to reshape, but z and x both share the same memory location?
# always changes x, always shares memory with the original tensor.
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [52]:
x # but x stays the same...

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
# so what does it mean to share memory location?
# it means if you change element in one, it will show in the other
x[0] = 3
x, z, x_reshape # both x and z have 3 changed.
# x_reshape is also changed because is in this instance pytorch decided to do that.

(tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [54]:
x_reshape = x_reshape.clone()
x[0] = 4
x, z, x_reshape # clone() method makes sure x_reshape is not altered

(tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[4., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [55]:
# Stack - concatenating tensors
# dimensions must be compatible.
x_stacked = torch.stack([x,x,x])
x_stacked # just made this a matrix

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
# torch.stack([x,z]) # cant stack bc. dimensions incompatible

In [57]:
# stacks tensors on top of each other.
torch.vstack([x,x])

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
# still stacking tensors, makes more rows.
torch.vstack([x.reshape(9,1), x.reshape(9,1)])

tensor([[4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.],
        [4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [59]:
# hstack puts each element of the second tensor in a new column of the first tensor.
torch.hstack([x,x])

tensor([4., 2., 3., 4., 5., 6., 7., 8., 9., 4., 2., 3., 4., 5., 6., 7., 8., 9.])

In [60]:
# the second tensor is added to the second col of each row in the first tensor
# no additional rows are created.
torch.hstack([x.reshape(9,1), x.reshape(9,1)])

tensor([[4., 4.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [61]:
# Squeeze - takes out all the one dimensions
# shares memory with the original tensor, so modifications will echo.
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
x_reshape.squeeze(), x_reshape.squeeze().shape # 1 dimension has been taken away

(tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [63]:
x_reshape_squeezed = x_reshape.squeeze()
x_reshape_squeezed[0] = 50
x_reshape_squeezed[0], x_reshape[0] # both were modified

(tensor(50.), tensor([50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [64]:
# adds a dimension 1 at the 0th index of dimension
 # [9] goes to [1,9]
x_reshape.squeeze().unsqueeze(dim=0), x_reshape.squeeze().unsqueeze(dim=0).shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [65]:
# adds a dimension of 1 at 1th index of dimension
 # [9] goes to [9,1]
x_reshape.squeeze().unsqueeze(dim=1), x_reshape.squeeze().unsqueeze(dim=1).shape

(tensor([[50.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [66]:
# negative values for dimension just count from last index
# -2 means 1 before the last index (-1)
# [9] => [1,9]
x_reshape.squeeze().unsqueeze(dim=-2), x_reshape.squeeze().unsqueeze(dim=-2).shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [67]:
x_reshape.squeeze().unsqueeze(dim=-1), x_reshape.squeeze().unsqueeze(dim=-1).shape

(tensor([[50.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [68]:
# Permute - switch order of dimensions
# permuted versions always share the same memory as the original, so modifications echo.
x = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]
# permute original tensor to rearrange axis (or dim) order
x_permuted = x.permute(2, 0, 1) # [color_channels, height, width]
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [69]:
x[0,0,0], x_permuted[0,0,0]

(tensor(0.5019), tensor(0.5019))

In [70]:
x[0,0,0] = 0.35
x[0,0,0], x_permuted[0,0,0]

(tensor(0.3500), tensor(0.3500))

In [71]:
w = torch.rand(2,2,3) # 2, 2x3 matrices
w

tensor([[[0.6278, 0.8115, 0.7902],
         [0.0035, 0.4343, 0.5796]],

        [[0.4768, 0.1992, 0.1346],
         [0.7112, 0.0127, 0.3226]]])

In [72]:
w[0, :, :], w[:, 0, :], w[:, :, 0]
# 0th matrix, just first rows, just the first columns

(tensor([[0.6278, 0.8115, 0.7902],
         [0.0035, 0.4343, 0.5796]]),
 tensor([[0.6278, 0.8115, 0.7902],
         [0.4768, 0.1992, 0.1346]]),
 tensor([[0.6278, 0.0035],
         [0.4768, 0.7112]]))

In [73]:
# when you permute with dimensions
# along dim2 (the columns)
# so if you put dim2 first in the permutation, this is what you end up with.
w[:, :, 0], w[:, :, 1], w[:, :, 2]

(tensor([[0.6278, 0.0035],
         [0.4768, 0.7112]]),
 tensor([[0.8115, 0.4343],
         [0.1992, 0.0127]]),
 tensor([[0.7902, 0.5796],
         [0.1346, 0.3226]]))

In [74]:
w.permute(2, 0, 1) # 3, 2x2 matrices

tensor([[[0.6278, 0.0035],
         [0.4768, 0.7112]],

        [[0.8115, 0.4343],
         [0.1992, 0.0127]],

        [[0.7902, 0.5796],
         [0.1346, 0.3226]]])

In [75]:
# if you put dim1 (rows)
w[:, 0, :], w[:, 1, :]

(tensor([[0.6278, 0.8115, 0.7902],
         [0.4768, 0.1992, 0.1346]]),
 tensor([[0.0035, 0.4343, 0.5796],
         [0.7112, 0.0127, 0.3226]]))

In [76]:
w.permute(1,2,0) # rearrangment

tensor([[[0.6278, 0.4768],
         [0.8115, 0.1992],
         [0.7902, 0.1346]],

        [[0.0035, 0.7112],
         [0.4343, 0.0127],
         [0.5796, 0.3226]]])

## Indexing

In [77]:
x = torch.arange(1, 10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [78]:
# index
x[0] # the first matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0,0] # first matrix, first row

tensor([1, 2, 3])

In [80]:
x[0,1,0] # first matrix, second row, first column

tensor(4)

In [81]:
# or
x[0][0] # does the same thing.

tensor([1, 2, 3])

In [82]:
x[:, :, 1] # all matrices, all rows, only col 1

tensor([[2, 5, 8]])

In [83]:
x[0, :, 0:2] # only two columns

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [84]:
torch.rand(3,3)

tensor([[0.7899, 0.3649, 0.9725],
        [0.6235, 0.2423, 0.7218],
        [0.3780, 0.9850, 0.0473]])

## PyTorch and Numpy

Numpy is popular, learn how to go between pytorch and numpy.

In [85]:
array = np.array([(1,2,3),(1,2,3),(1,2,3)])
array, type(array[0][0])

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 numpy.int64)

In [86]:
# make a tensor
array_tensor = torch.from_numpy(array)
array_tensor, array_tensor.dtype # boom, it's a tensor ahahaha

(tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]),
 torch.int64)

In [87]:
# note: by default, numpy datatype is float64 and any tensor created from them will cast to that type.
torch.from_numpy(np.array([1.0,9.0])) #float64, not torch default torch float32

tensor([1., 9.], dtype=torch.float64)

In [88]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor #numpy array is float32 just like tensor defualt.

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

Taking the random out of random.
- start with random numbers -> tensor operations -> update the numbers -> repeat until good
- sometimes you dont want so much randomness.
- reduce neural network randomness, use **random seed**

In [89]:
torch.rand(3,3)

tensor([[0.3263, 0.4249, 0.4956],
        [0.6787, 0.1990, 0.5605],
        [0.1769, 0.5723, 0.9636]])

In [90]:
 # highly unlikely to generate the same random numbers in two arrays
 rand_A = torch.rand(3,4)
 rand_B = torch.rand(3,4)
 print(rand_A)
 rand_A == rand_B # none of the values match w/ each other.

tensor([[0.7413, 0.2563, 0.5072, 0.0057],
        [0.8535, 0.6458, 0.9782, 0.9276],
        [0.8994, 0.5989, 0.3406, 0.9702]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [91]:
# important note: use RANDOM SEED once at the start of each cell
# or the arrays will be the same

RANDOM_SEED = 42 # common flavor for randomness
# makes the randomness reproducible across users.

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3,4)
print(C) # with random seed, ALWAYS produces the same thing.
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

C == D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPUs

GPUs - faster computation on numbers, thanks to CUDA + NVIDA hardware and pytorch optimization

We want our tensors & models on the GPU is because using GPU results in faster computations.

In [92]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [100]:
# count number of devices
torch.cuda.device_count()

1

In [96]:
tensor = torch.rand(1,3)
tensor, tensor.device # by default, tensors are created on the CPU.

(tensor([[0.2666, 0.6274, 0.2696]]), device(type='cpu'))

In [99]:
# move the tensor to the GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # this tensor will move to whatever device we need it on.

tensor([[0.2666, 0.6274, 0.2696]], device='cuda:0')

In [105]:
# move the tensor back to the CPU
# if tensor on GPU, can't transform to numpy: tensor_on_gpu.numpy()
array_on_cpu = tensor_on_gpu.cpu().numpy()
array_on_cpu

array([[0.26658005, 0.62744915, 0.26963168]], dtype=float32)

# Exercises

In [110]:
# access documentation
?torch.Tensor
?torch.cuda

In [114]:
# rand tensor
A = torch.rand(7,7)
B = torch.rand(1,7)
A @ B.T

tensor([[2.7141],
        [2.5875],
        [2.1447],
        [1.5684],
        [2.2803],
        [1.9907],
        [2.0582]])

In [116]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
A = torch.rand(7,7)
B = torch.rand(1,7)
A @ B.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [147]:
torch.manual_seed(1234) # generating random numbers
torch.cuda.manual_seed(1234) # generating random numbers for the GPU

C = torch.rand([2, 3], device="cuda")
D = torch.rand([2, 3], device="cuda")
C, D

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [159]:
product = D.T @ C
product

tensor([[0.1525, 0.5374, 0.4462],
        [0.4531, 0.2079, 0.6783],
        [0.2796, 0.3640, 0.5284]], device='cuda:0')

In [160]:
product.min(), product.argmin(), product.max(), product.argmax()

(tensor(0.1525, device='cuda:0'),
 tensor(0, device='cuda:0'),
 tensor(0.6783, device='cuda:0'),
 tensor(5, device='cuda:0'))

In [166]:
torch.manual_seed(7)
with_dims = torch.rand(1,1,1,10)
with_dims, with_dims.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [167]:
with_dims.squeeze(), with_dims.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))