<a href="https://colab.research.google.com/github/kaurarshmeet/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

2.6.0+cu124


## Different kinds of tensors:
*   Scalar = one number
*   Tensor = a tupule

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim # 0 dimensions for a scalar.

0

In [7]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim # 1 dimensions for a vector.

1

In [9]:
vector.shape # 2 by 1 => 2 elements in the vector.

torch.Size([2])

In [10]:
# matrix - a group of vectors.
MATRIX = torch.tensor(
    [[7,8],
    [9,10]]
)
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim # 2

2

In [12]:
MATRIX.shape # 2 by 2

torch.Size([2, 2])

In [13]:
# Tensor - a group of matrices
TENSOR = torch.tensor(
    [[
        [[1,2,3],
       [3,6,9]],

        [[1,3,4],
         [1,3,4]]

        ],

        [
           [[1,3,2],
            [1,5,8]],

           [[1,2,3],
            [4,5,6]]
        ]
     ]
)

TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9]],

         [[1, 3, 4],
          [1, 3, 4]]],


        [[[1, 3, 2],
          [1, 5, 8]],

         [[1, 2, 3],
          [4, 5, 6]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape # 2 sets of 2 (2 x 3 matrices).

torch.Size([2, 2, 2, 3])

## Random Tensors

* Many neural networks start with tensors full of random numbers, then update those to better understand data.

In [16]:
# by default, they will be float data type.
random_tensor = torch.rand(2, 3, 4) # 2 (3 x 4 matrices) filled with random numbers.
random_tensor

tensor([[[0.4940, 0.0835, 0.9763, 0.6640],
         [0.7347, 0.4051, 0.1806, 0.4757],
         [0.5409, 0.3603, 0.2633, 0.7202]],

        [[0.2850, 0.1501, 0.3118, 0.4429],
         [0.8865, 0.7812, 0.8644, 0.9535],
         [0.4466, 0.3458, 0.1841, 0.3246]]])

In [17]:
zeros = torch.zeros(size=(2,3,4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
# multiplying two tensors
random_tensor * zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
random_tensor.dtype

torch.float32

## Creating a Range of Tensors

In [20]:
# creating a tensor from the range.
# arange(start, stop, step)
# [start, start + step...stop) not end-inclusive.
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
skipping = torch.arange(0,10,2)
skipping

tensor([0, 2, 4, 6, 8])

In [22]:
# Create a copy tensor (in terms of shape)

# creates a tensor with the same shape.
ten_zeros = torch.zeros_like(input=skipping)
ten_zeros

ten_ones = torch.ones_like(input = skipping)
ten_ones

tensor([1, 1, 1, 1, 1])

## Tensor Datatypes

Big issues in PyTorch / deep learning
1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on right device.

In [23]:
float_32_tensor = torch.rand(2,3)
float_32_tensor.dtype # by default, float 32.

torch.float32

In [24]:
# tensor fields - don't always have to specify these.
fields = torch.tensor([1,3,3],
                      dtype=None, # still creates float 32 by default.
                                  # may want to demote to torch.half to run faster
                                  # upgrade to torch.double for more precision.
                      device = None, # what device is the tensor on
                      requires_grad = False) # whether or not to track gradients with tensor operations

In [25]:
float_16_tensor = fields.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
fields * float_16_tensor # everything gets depreciated to float16
# sometimes it works
# sometimes it dont work

tensor([1., 9., 9.], dtype=torch.float16)

## Tensor Attributes

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [28]:
# still works!
float_16_tensor * int_32_tensor

tensor([ 3., 18., 27.], dtype=torch.float16)

Important information from tensors:
- just use the instance variables
`tensor.dtype`,   `tensor.shape`,   `tensor.device`

In [29]:
# getting information from tensors

some_tensor = torch.rand(3,4)
some_tensor.dtype, some_tensor.shape, some_tensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

## Manipulating Tensors / Tensor Operations

Tensor Operations:
- addition, subtraction, multiplication element wise, division
- matrix multiplication

In [30]:
# addition
tensor = torch.tensor([1,2,3])
tensor + 10 # adds 10 to each element.

tensor([11, 12, 13])

In [31]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [32]:
# subtraction
tensor - 10

tensor([-9, -8, -7])

In [33]:
# pytorch inbuilt functions
# generally, just use the operators.
torch.mul(tensor, 10) # multiplication

tensor([10, 20, 30])

In [34]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two conditions

- (anything1, n) @ (n, anything2) is good.
- resulting shape will be (anything1, anything2)

In [35]:
 print(tensor)
 tensor * tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [36]:
# even though tensor is (1, 2, 3), when you square it
# it'll assume (1 2 3) horizontal and (1) vertical
                                     #(2)
                                     #(3)
torch.matmul(tensor, tensor) # clearer

tensor(14)

In [37]:
# mm won't work here because it's not flipping horizontal and vertical here
# torch.mm(tensor,tensor)

# this will work because dimensions are explicitly correct.
torch.mm(torch.rand(3,2), torch.rand(2,4))

tensor([[0.8649, 0.3702, 0.0831, 0.0767],
        [0.8853, 0.3386, 0.1537, 0.2863],
        [0.1329, 0.0478, 0.0282, 0.0585]])

In [38]:
tensor @ tensor # same thing

tensor(14)

In [39]:
# multiplication by hand
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

tensor(14)

In [40]:
tensor[i] # each tensor element is a scalar, tensor data type though.

tensor(3)

In [41]:
# implementing the matrix multiplication
A = torch.tensor([[1,2],
                  [3,4],
                  [5,6]]) # 3 x 2
B = torch.tensor([[7,8],
                  [9,10],
                  [11,12]]) # 3 x 2
# fixing shape issues => take the transpose
B.T # columns become rows, 2 x 3

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [42]:
B.T @ A # 2 x 2

tensor([[ 89, 116],
        [ 98, 128]])

## Min, Max, etc.

In [44]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
torch.min(x), x.min() # same thing.

(tensor(0), tensor(0))

In [46]:
# same thing for max

In [47]:
# torch.mean function requires tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) # need to convert to float for the mean.

tensor(45.)

In [48]:
# finding position in tensor which has the minimum value
x.argmin() # tensor(0) means index 0

tensor(0)

In [49]:
x.argmax(), x[9] # index 9

(tensor(9), tensor(90))

# Reshaping, Viewing, Stacking

* Reshaping - reshaping input tensors to another shape.
* View - shares memory with original tensor.
* Stacking - combine multiple tensors on top of each other
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions swapped in a certain way.

In [50]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [51]:
# Reshaping - reshape dimensions, must be compatible with original size.
# may or may not share memory with original tensor.
# x_reshape = x.reshape(1,7) # invalid bc we have more than 7 elements.
x_reshape = x.reshape(9,1) # we have 9 elements so fine.
x_reshape
x_reshape = x.reshape(3,3) # we have 9 elements, also fine
x_reshape

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [52]:
# View - very similar to reshape, but z and x both share the same memory location?
# always changes x, always shares memory with the original tensor.
z = x.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [53]:
x # but x stays the same...

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
# so what does it mean to share memory location?
# it means if you change element in one, it will show in the other
x[0] = 3
x, z, x_reshape # both x and z have 3 changed.
# x_reshape is also changed because is in this instance pytorch decided to do that.

(tensor([3., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [55]:
x_reshape = x_reshape.clone()
x[0] = 4
x, z, x_reshape # clone() method makes sure x_reshape is not altered

(tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[4., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[3., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [56]:
# Stack - concatenating tensors
# dimensions must be compatible.
x_stacked = torch.stack([x,x,x])
x_stacked # just made this a matrix

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# torch.stack([x,z]) # cant stack bc. dimensions incompatible

In [58]:
# stacks tensors on top of each other.
torch.vstack([x,x])

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [59]:
# still stacking tensors, makes more rows.
torch.vstack([x.reshape(9,1), x.reshape(9,1)])

tensor([[4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.],
        [4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [60]:
# hstack puts each element of the second tensor in a new column of the first tensor.
torch.hstack([x,x])

tensor([4., 2., 3., 4., 5., 6., 7., 8., 9., 4., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
# the second tensor is added to the second col of each row in the first tensor
# no additional rows are created.
torch.hstack([x.reshape(9,1), x.reshape(9,1)])

tensor([[4., 4.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [62]:
# Squeeze - takes out all the one dimensions
# shares memory with the original tensor, so modifications will echo.
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
x_reshape.squeeze(), x_reshape.squeeze().shape # 1 dimension has been taken away

(tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [64]:
x_reshape_squeezed = x_reshape.squeeze()
x_reshape_squeezed[0] = 50
x_reshape_squeezed[0], x_reshape[0] # both were modified

(tensor(50.), tensor([50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [65]:
# adds a dimension 1 at the 0th index of dimension
 # [9] goes to [1,9]
x_reshape.squeeze().unsqueeze(dim=0), x_reshape.squeeze().unsqueeze(dim=0).shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [66]:
# adds a dimension of 1 at 1th index of dimension
 # [9] goes to [9,1]
x_reshape.squeeze().unsqueeze(dim=1), x_reshape.squeeze().unsqueeze(dim=1).shape

(tensor([[50.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [67]:
# negative values for dimension just count from last index
# -2 means 1 before the last index (-1)
# [9] => [1,9]
x_reshape.squeeze().unsqueeze(dim=-2), x_reshape.squeeze().unsqueeze(dim=-2).shape

(tensor([[50.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]), torch.Size([1, 9]))

In [68]:
x_reshape.squeeze().unsqueeze(dim=-1), x_reshape.squeeze().unsqueeze(dim=-1).shape

(tensor([[50.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.]]),
 torch.Size([9, 1]))

In [69]:
# Permute - switch order of dimensions
# permuted versions always share the same memory as the original, so modifications echo.
x = torch.rand(size = (224, 224, 3)) # [height, width, color_channels]
# permute original tensor to rearrange axis (or dim) order
x_permuted = x.permute(2, 0, 1) # [color_channels, height, width]
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [70]:
x[0,0,0], x_permuted[0,0,0]

(tensor(0.9273), tensor(0.9273))

In [71]:
x[0,0,0] = 0.35
x[0,0,0], x_permuted[0,0,0]

(tensor(0.3500), tensor(0.3500))

In [96]:
w = torch.rand(2,2,3) # 2, 2x3 matrices
w

tensor([[[0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994]],

        [[0.5472, 0.0062, 0.9516],
         [0.0753, 0.8860, 0.5832]]])

In [102]:
w[0, :, :], w[:, 0, :], w[:, :, 0]
# 0th matrix, just first rows, just the first columns

(tensor([[0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994]]),
 tensor([[0.2969, 0.8317, 0.1053],
         [0.5472, 0.0062, 0.9516]]),
 tensor([[0.2969, 0.2695],
         [0.5472, 0.0753]]))

In [107]:
# when you permute with dimensions
# along dim2 (the columns)
# so if you put dim2 first in the permutation, this is what you end up with.
w[:, :, 0], w[:, :, 1], w[:, :, 2]

(tensor([[0.2969, 0.2695],
         [0.5472, 0.0753]]),
 tensor([[0.8317, 0.3588],
         [0.0062, 0.8860]]),
 tensor([[0.1053, 0.1994],
         [0.9516, 0.5832]]))

In [112]:
w.permute(2, 0, 1) # 3, 2x2 matrices

tensor([[[0.2969, 0.2695],
         [0.5472, 0.0753]],

        [[0.8317, 0.3588],
         [0.0062, 0.8860]],

        [[0.1053, 0.1994],
         [0.9516, 0.5832]]])

In [110]:
# if you put dim1 (rows)
w[:, 0, :], w[:, 1, :]

(tensor([[0.2969, 0.8317, 0.1053],
         [0.5472, 0.0062, 0.9516]]),
 tensor([[0.2695, 0.3588, 0.1994],
         [0.0753, 0.8860, 0.5832]]))

In [116]:
w.permute(1,2,0) # rearrangment

tensor([[[0.2969, 0.5472],
         [0.8317, 0.0062],
         [0.1053, 0.9516]],

        [[0.2695, 0.0753],
         [0.3588, 0.8860],
         [0.1994, 0.5832]]])

## Indexing

In [72]:
x = torch.arange(1, 10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [73]:
# index
x[0] # the first matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
x[0,0] # first matrix, first row

tensor([1, 2, 3])

In [75]:
x[0,1,0] # first matrix, second row, first column

tensor(4)

In [76]:
# or
x[0][0] # does the same thing.

tensor([1, 2, 3])

In [77]:
x[:, :, 1] # all matrices, all rows, only col 1

tensor([[2, 5, 8]])

In [78]:
x[0, :, 0:2] # only two columns

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [79]:
torch.rand(3,3)

tensor([[0.4982, 0.5707, 0.4637],
        [0.5243, 0.9373, 0.9771],
        [0.0241, 0.9469, 0.8924]])

## PyTorch and Numpy

Numpy is popular, learn how to go between pytorch and numpy.

In [80]:
array = np.array([(1,2,3),(1,2,3),(1,2,3)])
array, type(array[0][0])

(array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 numpy.int64)

In [81]:
# make a tensor
array_tensor = torch.from_numpy(array)
array_tensor, array_tensor.dtype # boom, it's a tensor ahahaha

(tensor([[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]),
 torch.int64)

In [82]:
# note: by default, numpy datatype is float64 and any tensor created from them will cast to that type.
torch.from_numpy(np.array([1.0,9.0])) #float64, not torch default torch float32

tensor([1., 9.], dtype=torch.float64)

In [83]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor #numpy array is float32 just like tensor defualt.

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

Taking the random out of random.
- start with random numbers -> tensor operations -> update the numbers -> repeat until good
- sometimes you dont want so much randomness.
- reduce neural network randomness, use **random seed**

In [84]:
torch.rand(3,3)

tensor([[0.7709, 0.4783, 0.9611],
        [0.9269, 0.7522, 0.3058],
        [0.9160, 0.3939, 0.9485]])

In [85]:
 # highly unlikely to generate the same random numbers in two arrays
 rand_A = torch.rand(3,4)
 rand_B = torch.rand(3,4)
 print(rand_A)
 rand_A == rand_B # none of the values match w/ each other.

tensor([[0.4551, 0.9818, 0.8126, 0.3469],
        [0.0295, 0.5840, 0.6563, 0.1038],
        [0.7930, 0.2958, 0.7382, 0.9819]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [126]:
# important note: use RANDOM SEED once at the start of each cell
# or the arrays will be the same

RANDOM_SEED = 42 # common flavor for randomness
# makes the randomness reproducible across users.

torch.manual_seed(RANDOM_SEED)
C = torch.rand(3,4)
print(C) # with random seed, ALWAYS produces the same thing.
torch.manual_seed(RANDOM_SEED)
D = torch.rand(3, 4)

C == D

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPUs

GPUs - faster computation on numbers, thanks to CUDA + NVIDA hardware and pytorch optimization